Repository ISISComputingGroup/EPICS-Cryosms, pull requests merged in 2020-02, with the labels that each got.

#2 Ticket 4831 cryosms simple start
  CRYOSMSApp/src/CRYOSMSDriver.cpp
  CRYOSMSApp/src/CRYOSMSDriver.h
  CRYOSMSApp/src/Makefile
  CRYOSMSApp/src/tests/CRYOSMSTests.cc
  CRYOSMSApp/src/tests/run_all_tests.cc
  Makefile
  configure/RELEASE
  cryosmsSup/cryosms.db
  cryosmsSup/cryosms.proto
  ramps/test.txt
  run_tests.bat
Labels: size/XL

#5 Update cryosms.db
  cryosmsSup/cryosms.db
Labels: size/S

#6 fix build errors, now 3 RETERN_IF_ASYNERROR macros
  CRYOSMSApp/src/CRYOSMSDriver.cpp
  CRYOSMSApp/src/CRYOSMSDriver.h
Labels: size/L
