Repository ISISComputingGroup/EPICS-Cryosms, pull requests merged in 2020-11, with the labels that each got.

#11 Ticket5259 switch rates mid ramp
  CRYOSMSApp/src/CRYOSMSDriver.cpp
  CRYOSMSApp/src/CRYOSMSDriver.h
  CRYOSMSApp/src/QueuedStateMachine.h
  CRYOSMSApp/src/StateMachineDriver.h
  cryosmsSup/cryosms.db
  cryosmsSup/cryosms.proto
Labels: size/L

#14 replacing brace initialisers with standard () calls
  CRYOSMSApp/src/CRYOSMSDriver.cpp
Labels: size/M

#15 corrected order of operations in checkTToA, conversions in tests
  CRYOSMSApp/src/CRYOSMSDriver.cpp
  CRYOSMSApp/src/tests/CRYOSMSTests.cc
Labels: size/XS

#16 Remove odd quotations mark
  cryosmsSup/cryosms.db
Labels: size/XS
